### ISSUE TITLE
Install Flake8 & plugins

### ISSUE THREAD

**Issue by kwzrd** [kwzrd/aeroplane#1]
Setup a basic linting suite and run it in CI on pull requests and new commits on master.

**Comment by AdityaJ7** [comment]
Hi, I would like to work on this @kwzrd

**Comment by kwzrd** [comment]
Hi @AdityaJ7, thanks for your interest. I'm not currently sure where I'm going with this project, so I'm not looking for contributors. Hope that's ok!

**Comment by AdityaJ7** [comment]
sure @kwzrd thanks for letting me know!!

**Comment by kwzrd** [comment]
Closed via #3.
